FROM nginx:1.9

COPY nginx.conf /etc/nginx/conf.d/nginx.conf

# dockerfile uses `\` to escape, docker-compose uses $$ instead

CMD /bin/bash -c "envsubst '\${APP_NAME}' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
